### ISSUE TITLE
Caddy - Reverse Proxy

### ISSUE THREAD

**Issue by millie75** [TriliumNext/Docs#105]
Hi 

Whenever I setup a very simple reverse proxy for TriliumNext on Caddy, when I go to the url it is just a blank page.
The Caddy file is setup exactly the same for my other 20+ self hosted sites that work absolutely fine.

Is there something different that needs to be configured for Caddy reverse proxy for this app?

TriliumNext is installed on a LXC and works fine with IP:port , just blank page when try to setup with Caddy.

Did look at the documentation and Issues here for Caddy, but no documentation (not unusual for Caddy on selfhosted apps - no one thinks of us :-))

Does anyone have this working with Caddy?

Thanks

**Comment by Alumniminium** [comment]
Is this your issue? https://github.com/TriliumNext/Notes/issues/303

**Comment by millie75** [comment]
No not the same, works fine with ip:port to connect, the reverse proxy for caddy is just blank

![2024-08-12_16-50-38](https://github.com/user-attachments/assets/8fa8cf07-c174-4b4b-a215-b0444498d724)

**Comment by advisorgee** [comment]
It works fine for me on Caddy.

**Comment by millie75** [comment]
thanks it is working had to clear cache on browser

**Comment by millie75** [comment]
closed
