### ISSUE TITLE
Doc Review: Document.md

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Docs#32]
# Please ensure the following:<br>- Without any previous knowledge about Trilium, can I accomplish what's explained in the documentation by strictly following only what's written in it?<br>- Is the language clear and unambiguous?<br>- Any language issues/misspellings or deviation from terminology used elsewhere in docs?<br>- Are more screenshots needed?<br>- Is the division of the document well structured using headings?<br>- Are step by step instructions marked with numbered lists?<br>- Do existing screenshots reflect current version? If not, create new ones.

**Comment by root-hal9000** [comment]
I started working on this and would like a little feedback from folks in @TriliumNext/documentation 

In terms of the where this fits in the documentation, it feels like more advanced usage than the first bullet point in Basic Usage items of the TOC. I mean, would most regular users who start off with Trilium mess with this at all? For example, I self host and never had to mess with the db files: I don't imagine that a lot of folks just starting up and installing the desktop app would ever go here (or start mucking about with a SQLite database!) unless they were looking for something specific or had issues. I know it talks about the demo notes, which is important also for basic users, but the relevant docs for beginners link here anyway (I could also separate that section into its own file with screenshots for clarity on how to import it). So, do you guys think it's reasonable to move this into advanced usage?

Honestly I would even question calling it "Document" - the first reaction of a new user would be that "document" is something like a note, conceptually speaking - the fact that it comes before notes in the docs adds to that potential confusion. I would even just consider calling it what it is, the database. Any thoughts?

Then an actual question in terms of advanced usage: the "how to reset the document" section has a instruction for deleting **all** document files, in the plural, with `rm document.db*` -- most users wouldn't have multiple DBs, correct? I only have one.  In what advanced scenarios would one have multiples? In the meeting, I heard some people's different implementations to have multiple knowledge bases - is there a scenario where this applied? If so, that would need to be explicitly explained here - so if anyone can enlighten me on scenarios with multiple documents, please let me know so i can write it up.

Other than that, I will do the regular edits for language and also make it platform agnostic (e.g.: rm command only applies to linux)

**Comment by Alumniminium** [comment]
Definitely rename it to database.

If you split it up, you'll have to address all the notes that link to it and update those references. I don't think that's the best of ideas, at least for the initial review stage.

Making it platform agnostic would be as easy as removing the commands and instead just telling them where the data is located and to delete the files. Windows/Mac users will use their "Explorers" and linux users will just `rm` it. This is such a basic task, if you can't solve it, you also don't use a tree-based knowledge base that can be scripted internally. 

I think we can give our users some benefit of doubt there :D

**Comment by CobriMediaJulien** [comment]
+1 for rename it database.

we can make it platform agnostic. i mean for some new linux guys we can use zadams instructions and for windows guys you just tell them the path (i think windows is .appData).  I think also we can trust users with navigation but maybe i you can move it to advanced section.

I like your idea to link more usefull example files and so improving the learning curve.

**Comment by CrO2Cl2** [comment]
also +1 for calling it database. On the Multiple databases thing, I think they mean these 3 files as the "Document files" 
![image](https://github.com/user-attachments/assets/af4a8c88-49ed-4e3f-a5ce-1508f027b515)
Also completely agree on just telling the user to delete the DB file instead of step to step instructions

**Comment by root-hal9000** [comment]
agreed on all points above - I will changed it to database and update all references to it across all other pages. Also just point people to data directory for removal rather than showing the remove command for every platform lol
