### ISSUE TITLE
Doc Review: Release notes v0.48.md

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Docs#63]
# Please ensure the following:

1. Without any previous knowledge about Trilium, can I accomplish what's explained in the documentation by strictly following only what's written in it?
2. Is the language clear and unambiguous?
3. Any language issues/misspellings or deviation from terminology used elsewhere in docs?
4. Are more screenshots needed?
5. Is the division of the document well structured using headings?
6. Are step by step instructions marked with numbered lists?
7. Do existing screenshots reflect current version? If not, create new ones.

**Comment by Alumniminium** [comment]
1. N/A (Not Applicable for changelogs)
2. TBD
3. TBD
4. N/A
5. TBD
6. N/A
7. N/A

**Comment by Alumniminium** [comment]
1. N/A (Not Applicable for changelogs)
2. TBD
3. TBD
4. N/A
5. TBD
6. N/A
7. N/A

This being the only changelog page, I'd close this and discard the file.

**Comment by root-hal9000** [comment]
Yep. My original proposal was open PR to -review branch (which moves it to the peer review column in the project), someone else double checks/makes any other needed edits and then merges to initial review branch. When all issues are completed, merge initial review to main. But let me know if that sounds too clunky
