### ISSUE TITLE
Doc Review: ALL - Consistent Markdown

### ISSUE THREAD

**Issue by Alumniminium** [TriliumNext/Docs#89]
I think we should use consistent, simple, markdown syntax such as headings:

```
# Bookmarks
To easily access selected notes, you can bookmark them. See demo:

![](images/bookmarks.gif)

## Bookmark folder
...
```
instead of 

```
# Bookmarks
To easily access selected notes, you can bookmark them. See demo:

![](images/bookmarks.gif)

Bookmark folder
---------------
...
```

_As originally posted by @root-hal9000 in https://github.com/TriliumNext/Notes/discussions/188#discussioncomment-9975695_

**Comment by root-hal9000** [comment]
Thanks, I added this to the project readme along with other guidelines
